### ISSUE TITLE
Using without display

### ISSUE THREAD

**Issue by Chudson16** [cryham/kc4#1]
Trying to convert an ibm model m to usb with this project. How would one go about implementing this project without a display? Thanks

**Comment by cryham** [comment]
Well the whole point of this project is having LCD and all features on it. Without it you wouldn't need Teensy 4.0 either, which is quite expensive, and powerful for LCD.
I think you could use [kiibohd](https://github.com/kiibohd/controller). With less effort than removing all display code from here.
